package ru.mataprime.repository;

import ru.mataprime.model.Book;
import ru.mataprime.config.DatabaseConfig;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Set;

public class DatabaseDao {
    private final DatabaseConfig databaseConfig;

    public DatabaseDao(DatabaseConfig databaseConfig) {
        this.databaseConfig = databaseConfig;
    }

    public void createTableIfNotExists() {
        try {
            Statement statement = databaseConfig.getConnection().createStatement();
            String requestCreateTableIfNotExists = "CREATE TABLE IF NOT EXISTS books (" +
                    "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "name character varying, " +
                    "author character varying" +
                    ");";
            statement.execute(requestCreateTableIfNotExists);
            statement.close();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void batchInsert(Set<Book> books) {
        try {
            String sqlRequest = "INSERT INTO books (name, author) VALUES (?, ?);";
            PreparedStatement preparedStmt = databaseConfig.getConnection().prepareStatement(sqlRequest, new String[]{"id"});

            for (Book book : books) {
                preparedStmt.setString(1, book.getName());
                preparedStmt.setString(2, book.getAuthor());
                preparedStmt.addBatch();
            }
            preparedStmt.executeBatch();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
